# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build docker
        run: |
          docker-compose -f doc/docker-for-test/docker-compose.yml up -d
          sleep 10
      - name: run check
        run: |
          docker exec -it glue4 /home/glue_user/workspace/jupyter_workspace/fj-cdp/shell/run_pytest.sh
        
