# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build docker
        run: |
          docker-compose -f docker-compose-test.yml up -d
          sleep 10
      - name: run_check_bandit
        run: |
          docker exec glue4 /home/glue_user/workspace/fj-cdp/shell/run_check_bandit.sh
      - name: run_check_flake8
        run: |
          docker exec glue4 /home/glue_user/workspace/fj-cdp/shell/run_check_flake8.sh
      - name: run_check_mypy
        run: |
          docker exec glue4 /home/glue_user/workspace/fj-cdp/shell/run_check_mypy.sh
      - name: run_pytest
        run: |
          docker exec glue4 /home/glue_user/workspace/fj-cdp/shell/run_pytest.sh